### ISSUE TITLE
token.json: keep track of which app instance a token was requested for

### ISSUE THREAD

**Issue by DavidS-ovm** [overmindtech/cli#687]
Currently the token.json only stores a single token and switching between --app instances requires deleting the file.

The CLI should instead keep track of the instance the token came from when storing it in token.json to make switching frictionless.

**Comment by tphoney** [comment]
@dylanratcliffe @DavidS-ovm so i have been playing with this and i have a couple of issues. 

### multiple auth prompts
I run the 'explore command' i will be asked to authenticate, run through the rest of the command all is 👍.
Then if i run the 'query commmand' i will be asked to reauthenticate. This is because the scopes are different this sucks in terms of expected UX. 

### duplicate code in gateway
we re-use the authentication code in gateway for the assistant cli, this is dev only. but it will break when we update anything to do with the token.json file 

what do you guys think ?
